#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_SettingOptionSlot

#include "Basic.hpp"

#include "BPUI_SettingOptionSlot_classes.hpp"
#include "BPUI_SettingOptionSlot_parameters.hpp"


namespace SDK
{

// Function BPUI_SettingOptionSlot.BPUI_SettingOptionSlot_C.GetDisplayKeyFormattedText
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
// bool                                    bDoesAltRequired                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UBPUI_SettingOptionSlot_C::GetDisplayKeyFormattedText(const struct FKey& Key, bool bDoesAltRequired)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_SettingOptionSlot_C", "GetDisplayKeyFormattedText");

	Params::BPUI_SettingOptionSlot_C_GetDisplayKeyFormattedText Parms{};

	Parms.Key = std::move(Key);
	Parms.bDoesAltRequired = bDoesAltRequired;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BPUI_SettingOptionSlot.BPUI_SettingOptionSlot_C.ExecuteUbergraph_BPUI_SettingOptionSlot
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_SettingOptionSlot_C::ExecuteUbergraph_BPUI_SettingOptionSlot(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_SettingOptionSlot_C", "ExecuteUbergraph_BPUI_SettingOptionSlot");

	Params::BPUI_SettingOptionSlot_C_ExecuteUbergraph_BPUI_SettingOptionSlot Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_SettingOptionSlot.BPUI_SettingOptionSlot_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBPUI_SettingOptionSlot_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_SettingOptionSlot_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

