#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_ComboBoxListItem

#include "Basic.hpp"

#include "BPUI_ComboBoxListItem_classes.hpp"
#include "BPUI_ComboBoxListItem_parameters.hpp"


namespace SDK
{

// Function BPUI_ComboBoxListItem.BPUI_ComboBoxListItem_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_ComboBoxListItem_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_ComboBoxListItem_C", "PreConstruct");

	Params::BPUI_ComboBoxListItem_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_ComboBoxListItem.BPUI_ComboBoxListItem_C.ExecuteUbergraph_BPUI_ComboBoxListItem
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_ComboBoxListItem_C::ExecuteUbergraph_BPUI_ComboBoxListItem(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_ComboBoxListItem_C", "ExecuteUbergraph_BPUI_ComboBoxListItem");

	Params::BPUI_ComboBoxListItem_C_ExecuteUbergraph_BPUI_ComboBoxListItem Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

