#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_ComboBox_2

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HTGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPUI_ComboBox_2.BPUI_ComboBox_2_C
// 0x0010 (0x14E0 - 0x14D0)
class UBPUI_ComboBox_2_C final : public UHTUI_ComboBox
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x14D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BPUI_ComboBox_2(int32 EntryPoint);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPUI_ComboBox_2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPUI_ComboBox_2_C")
	}
	static class UBPUI_ComboBox_2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPUI_ComboBox_2_C>();
	}
};
DUMPER7_ASSERTS_UBPUI_ComboBox_2_C;

}

