#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_QuickMenuFragmentActive

#include "Basic.hpp"

#include "WB_QuickMenuFragmentActive_classes.hpp"
#include "WB_QuickMenuFragmentActive_parameters.hpp"


namespace SDK
{

// Function WB_QuickMenuFragmentActive.WB_QuickMenuFragmentActive_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuFragmentActive_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuFragmentActive_C", "PreConstruct");

	Params::WB_QuickMenuFragmentActive_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_QuickMenuFragmentActive.WB_QuickMenuFragmentActive_C.PlayDisappearAnim
// (BlueprintCallable, BlueprintEvent)

void UWB_QuickMenuFragmentActive_C::PlayDisappearAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuFragmentActive_C", "PlayDisappearAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_QuickMenuFragmentActive.WB_QuickMenuFragmentActive_C.PlayAppearAnim
// (BlueprintCallable, BlueprintEvent)

void UWB_QuickMenuFragmentActive_C::PlayAppearAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuFragmentActive_C", "PlayAppearAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_QuickMenuFragmentActive.WB_QuickMenuFragmentActive_C.ExecuteUbergraph_WB_QuickMenuFragmentActive
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuFragmentActive_C::ExecuteUbergraph_WB_QuickMenuFragmentActive(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuFragmentActive_C", "ExecuteUbergraph_WB_QuickMenuFragmentActive");

	Params::WB_QuickMenuFragmentActive_C_ExecuteUbergraph_WB_QuickMenuFragmentActive Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

