#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_QuickMenuSettings_OptionBtn

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HTGame_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_QuickMenuSettings_OptionBtn.WB_QuickMenuSettings_OptionBtn_C
// 0x0050 (0x0870 - 0x0820)
class UWB_QuickMenuSettings_OptionBtn_C final : public UHTUI_QuickMenuSettings_OptionBtn
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0820(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 ImgCheck_Naviable_Fx;                              // 0x0828(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ImgCheck_Naviable;                                 // 0x0830(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ImageSelected;                                     // 0x0838(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Hovered;                                     // 0x0840(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHTUINavigationWidget_YH*               HTUINavigationWidget_YH_42;                        // 0x0848(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           CanvasPanelSelected;                               // 0x0850(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Background;                                        // 0x0858(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       SelectAnim;                                        // 0x0860(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WB_QuickMenuSettings_OptionBtn(int32 EntryPoint);
	void BP_OnSelectionChanged(bool bSelected);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WB_QuickMenuSettings_OptionBtn_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WB_QuickMenuSettings_OptionBtn_C")
	}
	static class UWB_QuickMenuSettings_OptionBtn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_QuickMenuSettings_OptionBtn_C>();
	}
};
DUMPER7_ASSERTS_UWB_QuickMenuSettings_OptionBtn_C;

}

