#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_QuickMenuSettings_OptionBtn_Menu

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_QuickMenuSettings_OptionBtn_Menu.WB_QuickMenuSettings_OptionBtn_Menu_C
// 0x0010 (0x0830 - 0x0820)
class UWB_QuickMenuSettings_OptionBtn_Menu_C final : public UHTUI_QuickMenuSettings_OptionBtn
{
public:
	class UImage*                                 ImageSwapBadge;                                    // 0x0820(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WB_QuickMenuSettings_OptionBtn_Menu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WB_QuickMenuSettings_OptionBtn_Menu_C")
	}
	static class UWB_QuickMenuSettings_OptionBtn_Menu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_QuickMenuSettings_OptionBtn_Menu_C>();
	}
};
DUMPER7_ASSERTS_UWB_QuickMenuSettings_OptionBtn_Menu_C;

}

