#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_CommonTitleWidget

#include "Basic.hpp"

#include "UI_CommonTitleWidget_classes.hpp"
#include "UI_CommonTitleWidget_parameters.hpp"


SDK_NAMESPACE_START

// Function UI_CommonTitleWidget.UI_CommonTitleWidget_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry_Tick                                        (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime_Tick                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CommonTitleWidget_C::Tick(const struct FGeometry& MyGeometry_Tick, float InDeltaTime_Tick)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CommonTitleWidget_C", "Tick");

	Params::UI_CommonTitleWidget_C_Tick Parms{};

	Parms.MyGeometry_Tick = std::move(MyGeometry_Tick);
	Parms.InDeltaTime_Tick = InDeltaTime_Tick;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CommonTitleWidget.UI_CommonTitleWidget_C.ExecuteUbergraph_UI_CommonTitleWidget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CommonTitleWidget_C::ExecuteUbergraph_UI_CommonTitleWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CommonTitleWidget_C", "ExecuteUbergraph_UI_CommonTitleWidget");

	Params::UI_CommonTitleWidget_C_ExecuteUbergraph_UI_CommonTitleWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CommonTitleWidget.UI_CommonTitleWidget_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_CommonTitleWidget_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CommonTitleWidget_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_CommonTitleWidget.UI_CommonTitleWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_CommonTitleWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CommonTitleWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_CommonTitleWidget.UI_CommonTitleWidget_C.BP Open Anim
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_CommonTitleWidget_C::BP_Open_Anim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CommonTitleWidget_C", "BP Open Anim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_CommonTitleWidget.UI_CommonTitleWidget_C.BP Close Anim
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_CommonTitleWidget_C::BP_Close_Anim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CommonTitleWidget_C", "BP Close Anim");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
