#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_QuickMenuSettings_GamepadMenu

#include "Basic.hpp"

#include "WB_QuickMenuSettings_GamepadMenu_classes.hpp"
#include "WB_QuickMenuSettings_GamepadMenu_parameters.hpp"


SDK_NAMESPACE_START

// Function WB_QuickMenuSettings_GamepadMenu.WB_QuickMenuSettings_GamepadMenu_C.ExecuteUbergraph_WB_QuickMenuSettings_GamepadMenu
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_GamepadMenu_C::ExecuteUbergraph_WB_QuickMenuSettings_GamepadMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_GamepadMenu_C", "ExecuteUbergraph_WB_QuickMenuSettings_GamepadMenu");

	Params::WB_QuickMenuSettings_GamepadMenu_C_ExecuteUbergraph_WB_QuickMenuSettings_GamepadMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_QuickMenuSettings_GamepadMenu.WB_QuickMenuSettings_GamepadMenu_C.BP_OnOptionRemoved
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      OptionID_BP_OnOptionRemoved                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_GamepadMenu_C::BP_OnOptionRemoved(const class FName& OptionID_BP_OnOptionRemoved)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_GamepadMenu_C", "BP_OnOptionRemoved");

	Params::WB_QuickMenuSettings_GamepadMenu_C_BP_OnOptionRemoved Parms{};

	Parms.OptionID_BP_OnOptionRemoved = OptionID_BP_OnOptionRemoved;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_QuickMenuSettings_GamepadMenu.WB_QuickMenuSettings_GamepadMenu_C.BP_OnOptionButtonSelected
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UHTUI_QuickMenuSettings_OptionBtn*OptionButton_BP_OnOptionButtonSelected                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_GamepadMenu_C::BP_OnOptionButtonSelected(class UHTUI_QuickMenuSettings_OptionBtn* OptionButton_BP_OnOptionButtonSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_GamepadMenu_C", "BP_OnOptionButtonSelected");

	Params::WB_QuickMenuSettings_GamepadMenu_C_BP_OnOptionButtonSelected Parms{};

	Parms.OptionButton_BP_OnOptionButtonSelected = OptionButton_BP_OnOptionButtonSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_QuickMenuSettings_GamepadMenu.WB_QuickMenuSettings_GamepadMenu_C.BP_OnEditorModeStateChanged
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    InbIsEditing_BP_OnEditorModeStateChanged               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_GamepadMenu_C::BP_OnEditorModeStateChanged(bool InbIsEditing_BP_OnEditorModeStateChanged)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_GamepadMenu_C", "BP_OnEditorModeStateChanged");

	Params::WB_QuickMenuSettings_GamepadMenu_C_BP_OnEditorModeStateChanged Parms{};

	Parms.InbIsEditing_BP_OnEditorModeStateChanged = InbIsEditing_BP_OnEditorModeStateChanged;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_QuickMenuSettings_GamepadMenu.WB_QuickMenuSettings_GamepadMenu_C.BP_DeactivateFragmentWidget
// (Event, Public, BlueprintEvent)
// Parameters:
// class UOverlay*                         InOverlay_BP_DeactivateFragmentWidget                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   Index_BP_DeactivateFragmentWidget                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_GamepadMenu_C::BP_DeactivateFragmentWidget(class UOverlay* InOverlay_BP_DeactivateFragmentWidget, int32 Index_BP_DeactivateFragmentWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_GamepadMenu_C", "BP_DeactivateFragmentWidget");

	Params::WB_QuickMenuSettings_GamepadMenu_C_BP_DeactivateFragmentWidget Parms{};

	Parms.InOverlay_BP_DeactivateFragmentWidget = InOverlay_BP_DeactivateFragmentWidget;
	Parms.Index_BP_DeactivateFragmentWidget = Index_BP_DeactivateFragmentWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_QuickMenuSettings_GamepadMenu.WB_QuickMenuSettings_GamepadMenu_C.BP_DeactivateFragmentPointer
// (Event, Public, BlueprintEvent)

void UWB_QuickMenuSettings_GamepadMenu_C::BP_DeactivateFragmentPointer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_GamepadMenu_C", "BP_DeactivateFragmentPointer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_QuickMenuSettings_GamepadMenu.WB_QuickMenuSettings_GamepadMenu_C.BP_ActivateFragmentWidget
// (Event, Public, BlueprintEvent)
// Parameters:
// class UOverlay*                         InOverlay_BP_ActivateFragmentWidget                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   Index_BP_ActivateFragmentWidget                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_GamepadMenu_C::BP_ActivateFragmentWidget(class UOverlay* InOverlay_BP_ActivateFragmentWidget, int32 Index_BP_ActivateFragmentWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_GamepadMenu_C", "BP_ActivateFragmentWidget");

	Params::WB_QuickMenuSettings_GamepadMenu_C_BP_ActivateFragmentWidget Parms{};

	Parms.InOverlay_BP_ActivateFragmentWidget = InOverlay_BP_ActivateFragmentWidget;
	Parms.Index_BP_ActivateFragmentWidget = Index_BP_ActivateFragmentWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_QuickMenuSettings_GamepadMenu.WB_QuickMenuSettings_GamepadMenu_C.BP_ActivateFragmentPointer
// (Event, Public, BlueprintEvent)

void UWB_QuickMenuSettings_GamepadMenu_C::BP_ActivateFragmentPointer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_GamepadMenu_C", "BP_ActivateFragmentPointer");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
