#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_QuickMenuSettings_KeyboardMenu

#include "Basic.hpp"

#include "WB_QuickMenuSettings_KeyboardMenu_classes.hpp"
#include "WB_QuickMenuSettings_KeyboardMenu_parameters.hpp"


SDK_NAMESPACE_START

// Function WB_QuickMenuSettings_KeyboardMenu.WB_QuickMenuSettings_KeyboardMenu_C.ExecuteUbergraph_WB_QuickMenuSettings_KeyboardMenu
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_KeyboardMenu_C::ExecuteUbergraph_WB_QuickMenuSettings_KeyboardMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_KeyboardMenu_C", "ExecuteUbergraph_WB_QuickMenuSettings_KeyboardMenu");

	Params::WB_QuickMenuSettings_KeyboardMenu_C_ExecuteUbergraph_WB_QuickMenuSettings_KeyboardMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_QuickMenuSettings_KeyboardMenu.WB_QuickMenuSettings_KeyboardMenu_C.BP_OnOptionButtonSelected
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UHTUI_QuickMenuSettings_OptionBtn*OptionButton_BP_OnOptionButtonSelected                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_KeyboardMenu_C::BP_OnOptionButtonSelected(class UHTUI_QuickMenuSettings_OptionBtn* OptionButton_BP_OnOptionButtonSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_KeyboardMenu_C", "BP_OnOptionButtonSelected");

	Params::WB_QuickMenuSettings_KeyboardMenu_C_BP_OnOptionButtonSelected Parms{};

	Parms.OptionButton_BP_OnOptionButtonSelected = OptionButton_BP_OnOptionButtonSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_QuickMenuSettings_KeyboardMenu.WB_QuickMenuSettings_KeyboardMenu_C.BP_OnEditorModeStateChanged
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    InbIsEditing_BP_OnEditorModeStateChanged               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_KeyboardMenu_C::BP_OnEditorModeStateChanged(bool InbIsEditing_BP_OnEditorModeStateChanged)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_KeyboardMenu_C", "BP_OnEditorModeStateChanged");

	Params::WB_QuickMenuSettings_KeyboardMenu_C_BP_OnEditorModeStateChanged Parms{};

	Parms.InbIsEditing_BP_OnEditorModeStateChanged = InbIsEditing_BP_OnEditorModeStateChanged;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_QuickMenuSettings_KeyboardMenu.WB_QuickMenuSettings_KeyboardMenu_C.BP_DeactivateFragmentWidget
// (Event, Public, BlueprintEvent)
// Parameters:
// class UOverlay*                         InOverlay_BP_DeactivateFragmentWidget                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   Index_BP_DeactivateFragmentWidget                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_KeyboardMenu_C::BP_DeactivateFragmentWidget(class UOverlay* InOverlay_BP_DeactivateFragmentWidget, int32 Index_BP_DeactivateFragmentWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_KeyboardMenu_C", "BP_DeactivateFragmentWidget");

	Params::WB_QuickMenuSettings_KeyboardMenu_C_BP_DeactivateFragmentWidget Parms{};

	Parms.InOverlay_BP_DeactivateFragmentWidget = InOverlay_BP_DeactivateFragmentWidget;
	Parms.Index_BP_DeactivateFragmentWidget = Index_BP_DeactivateFragmentWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_QuickMenuSettings_KeyboardMenu.WB_QuickMenuSettings_KeyboardMenu_C.BP_ActivateFragmentWidget
// (Event, Public, BlueprintEvent)
// Parameters:
// class UOverlay*                         InOverlay_BP_ActivateFragmentWidget                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   Index_BP_ActivateFragmentWidget                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_KeyboardMenu_C::BP_ActivateFragmentWidget(class UOverlay* InOverlay_BP_ActivateFragmentWidget, int32 Index_BP_ActivateFragmentWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_KeyboardMenu_C", "BP_ActivateFragmentWidget");

	Params::WB_QuickMenuSettings_KeyboardMenu_C_BP_ActivateFragmentWidget Parms{};

	Parms.InOverlay_BP_ActivateFragmentWidget = InOverlay_BP_ActivateFragmentWidget;
	Parms.Index_BP_ActivateFragmentWidget = Index_BP_ActivateFragmentWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_QuickMenuSettings_KeyboardMenu.WB_QuickMenuSettings_KeyboardMenu_C.BndEvt__WB_QuickMenuSettings_KeyboardMenu_HTButton_122_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWB_QuickMenuSettings_KeyboardMenu_C::BndEvt__WB_QuickMenuSettings_KeyboardMenu_HTButton_122_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_KeyboardMenu_C", "BndEvt__WB_QuickMenuSettings_KeyboardMenu_HTButton_122_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
