#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LoginPlayerAnimBlueprint

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function LoginPlayerAnimBlueprint.LoginPlayerAnimBlueprint_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct LoginPlayerAnimBlueprint_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
DUMPER7_ASSERTS_LoginPlayerAnimBlueprint_C_AnimGraph;

}

