#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_Setting

#include "Basic.hpp"

#include "BPUI_Setting_classes.hpp"
#include "BPUI_Setting_parameters.hpp"


namespace SDK
{

// Function BPUI_Setting.BPUI_Setting_C.BndEvt__BPUI_Setting_BPUI_RadioBox_Table_3_K2Node_ComponentBoundEvent_0_OnRadioBoxUnCheckedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UHTUI_RadioBox*                   RadioBox                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBPUI_Setting_C::BndEvt__BPUI_Setting_BPUI_RadioBox_Table_3_K2Node_ComponentBoundEvent_0_OnRadioBoxUnCheckedEvent__DelegateSignature(class UHTUI_RadioBox* RadioBox)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_Setting_C", "BndEvt__BPUI_Setting_BPUI_RadioBox_Table_3_K2Node_ComponentBoundEvent_0_OnRadioBoxUnCheckedEvent__DelegateSignature");

	Params::BPUI_Setting_C_BndEvt__BPUI_Setting_BPUI_RadioBox_Table_3_K2Node_ComponentBoundEvent_0_OnRadioBoxUnCheckedEvent__DelegateSignature Parms{};

	Parms.RadioBox = RadioBox;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_Setting.BPUI_Setting_C.BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_6_K2Node_ComponentBoundEvent_1_OnSettingChooseComboBoxOptionDelegate__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UHTUI_SettingOptionSlot*          OptionSlotWidget                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const class FName&                      OptionID                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OptionIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OldIndex                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_Setting_C::BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_6_K2Node_ComponentBoundEvent_1_OnSettingChooseComboBoxOptionDelegate__DelegateSignature(class UHTUI_SettingOptionSlot* OptionSlotWidget, const class FName& OptionID, int32 OptionIndex, int32 OldIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_Setting_C", "BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_6_K2Node_ComponentBoundEvent_1_OnSettingChooseComboBoxOptionDelegate__DelegateSignature");

	Params::BPUI_Setting_C_BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_6_K2Node_ComponentBoundEvent_1_OnSettingChooseComboBoxOptionDelegate__DelegateSignature Parms{};

	Parms.OptionSlotWidget = OptionSlotWidget;
	Parms.OptionID = OptionID;
	Parms.OptionIndex = OptionIndex;
	Parms.OldIndex = OldIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_Setting.BPUI_Setting_C.BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_8_K2Node_ComponentBoundEvent_3_OnSettingChooseComboBoxOptionDelegate__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UHTUI_SettingOptionSlot*          OptionSlotWidget                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const class FName&                      OptionID                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OptionIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OldIndex                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_Setting_C::BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_8_K2Node_ComponentBoundEvent_3_OnSettingChooseComboBoxOptionDelegate__DelegateSignature(class UHTUI_SettingOptionSlot* OptionSlotWidget, const class FName& OptionID, int32 OptionIndex, int32 OldIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_Setting_C", "BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_8_K2Node_ComponentBoundEvent_3_OnSettingChooseComboBoxOptionDelegate__DelegateSignature");

	Params::BPUI_Setting_C_BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_8_K2Node_ComponentBoundEvent_3_OnSettingChooseComboBoxOptionDelegate__DelegateSignature Parms{};

	Parms.OptionSlotWidget = OptionSlotWidget;
	Parms.OptionID = OptionID;
	Parms.OptionIndex = OptionIndex;
	Parms.OldIndex = OldIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_Setting.BPUI_Setting_C.BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_K2Node_ComponentBoundEvent_2_OnSettingChooseComboBoxOptionDelegate__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UHTUI_SettingOptionSlot*          OptionSlotWidget                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const class FName&                      OptionID                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OptionIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OldIndex                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_Setting_C::BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_K2Node_ComponentBoundEvent_2_OnSettingChooseComboBoxOptionDelegate__DelegateSignature(class UHTUI_SettingOptionSlot* OptionSlotWidget, const class FName& OptionID, int32 OptionIndex, int32 OldIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_Setting_C", "BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_K2Node_ComponentBoundEvent_2_OnSettingChooseComboBoxOptionDelegate__DelegateSignature");

	Params::BPUI_Setting_C_BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_K2Node_ComponentBoundEvent_2_OnSettingChooseComboBoxOptionDelegate__DelegateSignature Parms{};

	Parms.OptionSlotWidget = OptionSlotWidget;
	Parms.OptionID = OptionID;
	Parms.OptionIndex = OptionIndex;
	Parms.OldIndex = OldIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_Setting.BPUI_Setting_C.BndEvt__BPUI_Setting_BtnRestore_K2Node_ComponentBoundEvent_24_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBPUI_Setting_C::BndEvt__BPUI_Setting_BtnRestore_K2Node_ComponentBoundEvent_24_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_Setting_C", "BndEvt__BPUI_Setting_BtnRestore_K2Node_ComponentBoundEvent_24_CommonButtonBaseClicked__DelegateSignature");

	Params::BPUI_Setting_C_BndEvt__BPUI_Setting_BtnRestore_K2Node_ComponentBoundEvent_24_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_Setting.BPUI_Setting_C.BP_OnActiveWidgetIndexSet
// (Event, Protected, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InIndex                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_Setting_C::BP_OnActiveWidgetIndexSet(int32 InIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_Setting_C", "BP_OnActiveWidgetIndexSet");

	Params::BPUI_Setting_C_BP_OnActiveWidgetIndexSet Parms{};

	Parms.InIndex = InIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_Setting.BPUI_Setting_C.BP_OnHandleBackAction
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UBPUI_Setting_C::BP_OnHandleBackAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_Setting_C", "BP_OnHandleBackAction");

	Params::BPUI_Setting_C_BP_OnHandleBackAction Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BPUI_Setting.BPUI_Setting_C.Completed_0B4F014D4A1E7F26BA9D62B573C497B9
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCommonActivatableWidget*         WidgetObject                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBPUI_Setting_C::Completed_0B4F014D4A1E7F26BA9D62B573C497B9(class UCommonActivatableWidget* WidgetObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_Setting_C", "Completed_0B4F014D4A1E7F26BA9D62B573C497B9");

	Params::BPUI_Setting_C_Completed_0B4F014D4A1E7F26BA9D62B573C497B9 Parms{};

	Parms.WidgetObject = WidgetObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_Setting.BPUI_Setting_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBPUI_Setting_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_Setting_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPUI_Setting.BPUI_Setting_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBPUI_Setting_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_Setting_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPUI_Setting.BPUI_Setting_C.ExecuteUbergraph_BPUI_Setting
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_Setting_C::ExecuteUbergraph_BPUI_Setting(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_Setting_C", "ExecuteUbergraph_BPUI_Setting");

	Params::BPUI_Setting_C_ExecuteUbergraph_BPUI_Setting Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_Setting.BPUI_Setting_C.MacFroceHideMouse
// (Public, BlueprintCallable, BlueprintEvent)

void UBPUI_Setting_C::MacFroceHideMouse()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_Setting_C", "MacFroceHideMouse");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPUI_Setting.BPUI_Setting_C.OnMsgBoxCancelDyamicDelegate_Event
// (BlueprintCallable, BlueprintEvent)

void UBPUI_Setting_C::OnMsgBoxCancelDyamicDelegate_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_Setting_C", "OnMsgBoxCancelDyamicDelegate_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPUI_Setting.BPUI_Setting_C.OnMsgBoxSure
// (BlueprintCallable, BlueprintEvent)

void UBPUI_Setting_C::OnMsgBoxSure()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_Setting_C", "OnMsgBoxSure");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPUI_Setting.BPUI_Setting_C.OnMsgBoxSureDyamicDelegate_Event
// (BlueprintCallable, BlueprintEvent)

void UBPUI_Setting_C::OnMsgBoxSureDyamicDelegate_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_Setting_C", "OnMsgBoxSureDyamicDelegate_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPUI_Setting.BPUI_Setting_C.OnSetCommonSubTitle
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      InText                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UBPUI_Setting_C::OnSetCommonSubTitle(const class FText& InText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_Setting_C", "OnSetCommonSubTitle");

	Params::BPUI_Setting_C_OnSetCommonSubTitle Parms{};

	Parms.InText = std::move(InText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_Setting.BPUI_Setting_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_Setting_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_Setting_C", "PreConstruct");

	Params::BPUI_Setting_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_Setting.BPUI_Setting_C.SequenceEvent
// (BlueprintCallable, BlueprintEvent)

void UBPUI_Setting_C::SequenceEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_Setting_C", "SequenceEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPUI_Setting.BPUI_Setting_C.SequenceEvent__ENTRYPOINTBPUI_Setting
// (Public, BlueprintCallable, BlueprintEvent)

void UBPUI_Setting_C::SequenceEvent__ENTRYPOINTBPUI_Setting()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_Setting_C", "SequenceEvent__ENTRYPOINTBPUI_Setting");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPUI_Setting.BPUI_Setting_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_Setting_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_Setting_C", "Tick");

	Params::BPUI_Setting_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

