#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_ComboBox_2

#include "Basic.hpp"


namespace SDK::Params
{

// Function BPUI_ComboBox_2.BPUI_ComboBox_2_C.ExecuteUbergraph_BPUI_ComboBox_2
// 0x0004 (0x0004 - 0x0000)
struct BPUI_ComboBox_2_C_ExecuteUbergraph_BPUI_ComboBox_2 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_ComboBox_2_C_ExecuteUbergraph_BPUI_ComboBox_2;

}

