#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_ProgressSliderSetting

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPUI_ProgressSliderSetting.BPUI_ProgressSliderSetting_C
// 0x0000 (0x0D00 - 0x0D00)
class UBPUI_ProgressSliderSetting_C final : public UHTUI_ProgressSlider
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPUI_ProgressSliderSetting_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPUI_ProgressSliderSetting_C")
	}
	static class UBPUI_ProgressSliderSetting_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPUI_ProgressSliderSetting_C>();
	}
};
DUMPER7_ASSERTS_UBPUI_ProgressSliderSetting_C;

}

