#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_QuickMenuSettings

#include "Basic.hpp"

#include "WB_QuickMenuSettings_classes.hpp"
#include "WB_QuickMenuSettings_parameters.hpp"


namespace SDK
{

// Function WB_QuickMenuSettings.WB_QuickMenuSettings_C.BndEvt__WB_QuickMenuSettings_BtnRestore_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_C::BndEvt__WB_QuickMenuSettings_BtnRestore_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_C", "BndEvt__WB_QuickMenuSettings_BtnRestore_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature");

	Params::WB_QuickMenuSettings_C_BndEvt__WB_QuickMenuSettings_BtnRestore_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_QuickMenuSettings.WB_QuickMenuSettings_C.BndEvt__WB_QuickMenuSettings_BtnSave_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_C::BndEvt__WB_QuickMenuSettings_BtnSave_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_C", "BndEvt__WB_QuickMenuSettings_BtnSave_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature");

	Params::WB_QuickMenuSettings_C_BndEvt__WB_QuickMenuSettings_BtnSave_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_QuickMenuSettings.WB_QuickMenuSettings_C.BndEvt__WB_QuickMenuSettings_HTKeysAction_34_K2Node_ComponentBoundEvent_0_OnClickedDelegate__DelegateSignature
// (BlueprintEvent)

void UWB_QuickMenuSettings_C::BndEvt__WB_QuickMenuSettings_HTKeysAction_34_K2Node_ComponentBoundEvent_0_OnClickedDelegate__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_C", "BndEvt__WB_QuickMenuSettings_HTKeysAction_34_K2Node_ComponentBoundEvent_0_OnClickedDelegate__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_QuickMenuSettings.WB_QuickMenuSettings_C.BP_OnEditorModeQuit
// (Event, Public, BlueprintEvent)

void UWB_QuickMenuSettings_C::BP_OnEditorModeQuit()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_C", "BP_OnEditorModeQuit");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_QuickMenuSettings.WB_QuickMenuSettings_C.BP_OnEditorModeStateChanged
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsEditing_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_C::BP_OnEditorModeStateChanged(bool IsEditing_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_C", "BP_OnEditorModeStateChanged");

	Params::WB_QuickMenuSettings_C_BP_OnEditorModeStateChanged Parms{};

	Parms.IsEditing_0 = IsEditing_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_QuickMenuSettings.WB_QuickMenuSettings_C.BP_OnOptionButtonSelected
// (Event, Public, BlueprintEvent)
// Parameters:
// class UHTUI_QuickMenuSettings_OptionBtn*OptionButton                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_C::BP_OnOptionButtonSelected(class UHTUI_QuickMenuSettings_OptionBtn* OptionButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_C", "BP_OnOptionButtonSelected");

	Params::WB_QuickMenuSettings_C_BP_OnOptionButtonSelected Parms{};

	Parms.OptionButton = OptionButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_QuickMenuSettings.WB_QuickMenuSettings_C.Completed_74A236574CC91A7111C1B0A0A4E604C5
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCommonActivatableWidget*         WidgetObject                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_C::Completed_74A236574CC91A7111C1B0A0A4E604C5(class UCommonActivatableWidget* WidgetObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_C", "Completed_74A236574CC91A7111C1B0A0A4E604C5");

	Params::WB_QuickMenuSettings_C_Completed_74A236574CC91A7111C1B0A0A4E604C5 Parms{};

	Parms.WidgetObject = WidgetObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_QuickMenuSettings.WB_QuickMenuSettings_C.Completed_A94BF164413CC66F2B059FA218835780
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCommonActivatableWidget*         WidgetObject                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_C::Completed_A94BF164413CC66F2B059FA218835780(class UCommonActivatableWidget* WidgetObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_C", "Completed_A94BF164413CC66F2B059FA218835780");

	Params::WB_QuickMenuSettings_C_Completed_A94BF164413CC66F2B059FA218835780 Parms{};

	Parms.WidgetObject = WidgetObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_QuickMenuSettings.WB_QuickMenuSettings_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWB_QuickMenuSettings_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_QuickMenuSettings.WB_QuickMenuSettings_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWB_QuickMenuSettings_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_QuickMenuSettings.WB_QuickMenuSettings_C.ExecuteUbergraph_WB_QuickMenuSettings
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_C::ExecuteUbergraph_WB_QuickMenuSettings(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_C", "ExecuteUbergraph_WB_QuickMenuSettings");

	Params::WB_QuickMenuSettings_C_ExecuteUbergraph_WB_QuickMenuSettings Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_QuickMenuSettings.WB_QuickMenuSettings_C.HandleBackAction
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   ret                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_C::HandleBackAction(bool* ret)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_C", "HandleBackAction");

	Params::WB_QuickMenuSettings_C_HandleBackAction Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ret != nullptr)
		*ret = Parms.ret;
}


// Function WB_QuickMenuSettings.WB_QuickMenuSettings_C.OnCancelMessageBox
// (BlueprintCallable, BlueprintEvent)

void UWB_QuickMenuSettings_C::OnCancelMessageBox()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_C", "OnCancelMessageBox");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_QuickMenuSettings.WB_QuickMenuSettings_C.OnMsgBoxCancelDyamicDelegate_Event
// (BlueprintCallable, BlueprintEvent)

void UWB_QuickMenuSettings_C::OnMsgBoxCancelDyamicDelegate_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_C", "OnMsgBoxCancelDyamicDelegate_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_QuickMenuSettings.WB_QuickMenuSettings_C.OnMsgBoxSureDyamicDelegate_Event
// (BlueprintCallable, BlueprintEvent)

void UWB_QuickMenuSettings_C::OnMsgBoxSureDyamicDelegate_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_C", "OnMsgBoxSureDyamicDelegate_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_QuickMenuSettings.WB_QuickMenuSettings_C.OnSureSaveMessageBox
// (BlueprintCallable, BlueprintEvent)

void UWB_QuickMenuSettings_C::OnSureSaveMessageBox()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_C", "OnSureSaveMessageBox");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_QuickMenuSettings.WB_QuickMenuSettings_C.SetQuickMenuVisable
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   isShow                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_C::SetQuickMenuVisable(bool* isShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_C", "SetQuickMenuVisable");

	Params::WB_QuickMenuSettings_C_SetQuickMenuVisable Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (isShow != nullptr)
		*isShow = Parms.isShow;
}


// Function WB_QuickMenuSettings.WB_QuickMenuSettings_C.ShowSaveMessageBox
// (BlueprintCallable, BlueprintEvent)

void UWB_QuickMenuSettings_C::ShowSaveMessageBox()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_C", "ShowSaveMessageBox");

	UObject::ProcessEvent(Func, nullptr);
}

}

