#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LoginPlayerAnimBlueprint

#include "Basic.hpp"

#include "LoginPlayerAnimBlueprint_classes.hpp"
#include "LoginPlayerAnimBlueprint_parameters.hpp"


SDK_NAMESPACE_START

// Function LoginPlayerAnimBlueprint.LoginPlayerAnimBlueprint_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph                                              (Parm, OutParm, NoDestructor)

void ULoginPlayerAnimBlueprint_C::AnimGraph(struct FPoseLink* AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginPlayerAnimBlueprint_C", "AnimGraph");

	Params::LoginPlayerAnimBlueprint_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph != nullptr)
		*AnimGraph = std::move(Parms.AnimGraph);
}


SDK_NAMESPACE_END
