#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace LoginPlayerAnimBlueprint { struct FAnimBlueprintGeneratedConstantData; }

namespace LoginPlayerAnimBlueprint_Male { struct FAnimBlueprintGeneratedConstantData; }

namespace GameplayAbilities { struct FServerAbilityRPCBatch; }

