#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_SettingOptionSlotCulture

#include "Basic.hpp"

#include "BPUI_SettingOptionSlotCulture_classes.hpp"
#include "BPUI_SettingOptionSlotCulture_parameters.hpp"


namespace SDK
{

// Function BPUI_SettingOptionSlotCulture.BPUI_SettingOptionSlotCulture_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBPUI_SettingOptionSlotCulture_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_SettingOptionSlotCulture_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPUI_SettingOptionSlotCulture.BPUI_SettingOptionSlotCulture_C.ExecuteUbergraph_BPUI_SettingOptionSlotCulture
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_SettingOptionSlotCulture_C::ExecuteUbergraph_BPUI_SettingOptionSlotCulture(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_SettingOptionSlotCulture_C", "ExecuteUbergraph_BPUI_SettingOptionSlotCulture");

	Params::BPUI_SettingOptionSlotCulture_C_ExecuteUbergraph_BPUI_SettingOptionSlotCulture Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_SettingOptionSlotCulture.BPUI_SettingOptionSlotCulture_C.GetDisplayKeyFormattedText
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
// bool                                    bDoesAltRequired                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UBPUI_SettingOptionSlotCulture_C::GetDisplayKeyFormattedText(const struct FKey& Key, bool bDoesAltRequired)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_SettingOptionSlotCulture_C", "GetDisplayKeyFormattedText");

	Params::BPUI_SettingOptionSlotCulture_C_GetDisplayKeyFormattedText Parms{};

	Parms.Key = std::move(Key);
	Parms.bDoesAltRequired = bDoesAltRequired;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

