#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_ComboBoxListItem_Culture

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "HTGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPUI_ComboBoxListItem_Culture.BPUI_ComboBoxListItem_Culture_C
// 0x0010 (0x0CD0 - 0x0CC0)
class UBPUI_ComboBoxListItem_Culture_C final : public UHTUI_ComboBoxListItem_Culture
{
public:
	struct FLinearColor                           NewVar;                                            // 0x0CC0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPUI_ComboBoxListItem_Culture_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPUI_ComboBoxListItem_Culture_C")
	}
	static class UBPUI_ComboBoxListItem_Culture_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPUI_ComboBoxListItem_Culture_C>();
	}
};
DUMPER7_ASSERTS_UBPUI_ComboBoxListItem_Culture_C;

}

