#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_LawSetting

#include "Basic.hpp"

#include "BPUI_LawSetting_classes.hpp"
#include "BPUI_LawSetting_parameters.hpp"


namespace SDK
{

// Function BPUI_LawSetting.BPUI_LawSetting_C.BndEvt__BPUI_LawSetting_BPUI_SettingOptionSlot_1_K2Node_ComponentBoundEvent_1_OnSettingOptionButtonClickDelegate__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UHTUI_SettingOptionSlot*          OptionSlotWidget                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const class FName&                      OptionID                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_LawSetting_C::BndEvt__BPUI_LawSetting_BPUI_SettingOptionSlot_1_K2Node_ComponentBoundEvent_1_OnSettingOptionButtonClickDelegate__DelegateSignature(class UHTUI_SettingOptionSlot* OptionSlotWidget, const class FName& OptionID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_LawSetting_C", "BndEvt__BPUI_LawSetting_BPUI_SettingOptionSlot_1_K2Node_ComponentBoundEvent_1_OnSettingOptionButtonClickDelegate__DelegateSignature");

	Params::BPUI_LawSetting_C_BndEvt__BPUI_LawSetting_BPUI_SettingOptionSlot_1_K2Node_ComponentBoundEvent_1_OnSettingOptionButtonClickDelegate__DelegateSignature Parms{};

	Parms.OptionSlotWidget = OptionSlotWidget;
	Parms.OptionID = OptionID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_LawSetting.BPUI_LawSetting_C.BndEvt__BPUI_LawSetting_BPUI_SettingOptionSlot_25_K2Node_ComponentBoundEvent_0_OnSettingChooseComboBoxOptionDelegate__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UHTUI_SettingOptionSlot*          OptionSlotWidget                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const class FName&                      OptionID                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OptionIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OldIndex                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_LawSetting_C::BndEvt__BPUI_LawSetting_BPUI_SettingOptionSlot_25_K2Node_ComponentBoundEvent_0_OnSettingChooseComboBoxOptionDelegate__DelegateSignature(class UHTUI_SettingOptionSlot* OptionSlotWidget, const class FName& OptionID, int32 OptionIndex, int32 OldIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_LawSetting_C", "BndEvt__BPUI_LawSetting_BPUI_SettingOptionSlot_25_K2Node_ComponentBoundEvent_0_OnSettingChooseComboBoxOptionDelegate__DelegateSignature");

	Params::BPUI_LawSetting_C_BndEvt__BPUI_LawSetting_BPUI_SettingOptionSlot_25_K2Node_ComponentBoundEvent_0_OnSettingChooseComboBoxOptionDelegate__DelegateSignature Parms{};

	Parms.OptionSlotWidget = OptionSlotWidget;
	Parms.OptionID = OptionID;
	Parms.OptionIndex = OptionIndex;
	Parms.OldIndex = OldIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_LawSetting.BPUI_LawSetting_C.BndEvt__BPUI_LawSetting_BPUI_SettingOptionSlot_K2Node_ComponentBoundEvent_2_OnSettingOptionButtonClickDelegate__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UHTUI_SettingOptionSlot*          OptionSlotWidget                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const class FName&                      OptionID                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_LawSetting_C::BndEvt__BPUI_LawSetting_BPUI_SettingOptionSlot_K2Node_ComponentBoundEvent_2_OnSettingOptionButtonClickDelegate__DelegateSignature(class UHTUI_SettingOptionSlot* OptionSlotWidget, const class FName& OptionID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_LawSetting_C", "BndEvt__BPUI_LawSetting_BPUI_SettingOptionSlot_K2Node_ComponentBoundEvent_2_OnSettingOptionButtonClickDelegate__DelegateSignature");

	Params::BPUI_LawSetting_C_BndEvt__BPUI_LawSetting_BPUI_SettingOptionSlot_K2Node_ComponentBoundEvent_2_OnSettingOptionButtonClickDelegate__DelegateSignature Parms{};

	Parms.OptionSlotWidget = OptionSlotWidget;
	Parms.OptionID = OptionID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_LawSetting.BPUI_LawSetting_C.BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_24_K2Node_ComponentBoundEvent_15_OnSettingOptionButtonClickDelegate__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UHTUI_SettingOptionSlot*          OptionSlotWidget                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const class FName&                      OptionID                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_LawSetting_C::BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_24_K2Node_ComponentBoundEvent_15_OnSettingOptionButtonClickDelegate__DelegateSignature(class UHTUI_SettingOptionSlot* OptionSlotWidget, const class FName& OptionID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_LawSetting_C", "BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_24_K2Node_ComponentBoundEvent_15_OnSettingOptionButtonClickDelegate__DelegateSignature");

	Params::BPUI_LawSetting_C_BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_24_K2Node_ComponentBoundEvent_15_OnSettingOptionButtonClickDelegate__DelegateSignature Parms{};

	Parms.OptionSlotWidget = OptionSlotWidget;
	Parms.OptionID = OptionID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_LawSetting.BPUI_LawSetting_C.BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_26_K2Node_ComponentBoundEvent_17_OnSettingChooseComboBoxOptionDelegate__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UHTUI_SettingOptionSlot*          OptionSlotWidget                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const class FName&                      OptionID                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OptionIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OldIndex                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_LawSetting_C::BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_26_K2Node_ComponentBoundEvent_17_OnSettingChooseComboBoxOptionDelegate__DelegateSignature(class UHTUI_SettingOptionSlot* OptionSlotWidget, const class FName& OptionID, int32 OptionIndex, int32 OldIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_LawSetting_C", "BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_26_K2Node_ComponentBoundEvent_17_OnSettingChooseComboBoxOptionDelegate__DelegateSignature");

	Params::BPUI_LawSetting_C_BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_26_K2Node_ComponentBoundEvent_17_OnSettingChooseComboBoxOptionDelegate__DelegateSignature Parms{};

	Parms.OptionSlotWidget = OptionSlotWidget;
	Parms.OptionID = OptionID;
	Parms.OptionIndex = OptionIndex;
	Parms.OldIndex = OldIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_LawSetting.BPUI_LawSetting_C.BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_3_K2Node_ComponentBoundEvent_14_OnSettingOptionButtonClickDelegate__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UHTUI_SettingOptionSlot*          OptionSlotWidget                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const class FName&                      OptionID                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_LawSetting_C::BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_3_K2Node_ComponentBoundEvent_14_OnSettingOptionButtonClickDelegate__DelegateSignature(class UHTUI_SettingOptionSlot* OptionSlotWidget, const class FName& OptionID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_LawSetting_C", "BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_3_K2Node_ComponentBoundEvent_14_OnSettingOptionButtonClickDelegate__DelegateSignature");

	Params::BPUI_LawSetting_C_BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_3_K2Node_ComponentBoundEvent_14_OnSettingOptionButtonClickDelegate__DelegateSignature Parms{};

	Parms.OptionSlotWidget = OptionSlotWidget;
	Parms.OptionID = OptionID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_LawSetting.BPUI_LawSetting_C.BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_CrossPlatform_K2Node_ComponentBoundEvent_46_OnSettingChooseComboBoxOptionDelegate__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UHTUI_SettingOptionSlot*          OptionSlotWidget                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const class FName&                      OptionID                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OptionIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OldIndex                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_LawSetting_C::BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_CrossPlatform_K2Node_ComponentBoundEvent_46_OnSettingChooseComboBoxOptionDelegate__DelegateSignature(class UHTUI_SettingOptionSlot* OptionSlotWidget, const class FName& OptionID, int32 OptionIndex, int32 OldIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_LawSetting_C", "BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_CrossPlatform_K2Node_ComponentBoundEvent_46_OnSettingChooseComboBoxOptionDelegate__DelegateSignature");

	Params::BPUI_LawSetting_C_BndEvt__BPUI_Setting_BPUI_SettingOptionSlot_CrossPlatform_K2Node_ComponentBoundEvent_46_OnSettingChooseComboBoxOptionDelegate__DelegateSignature Parms{};

	Parms.OptionSlotWidget = OptionSlotWidget;
	Parms.OptionID = OptionID;
	Parms.OptionIndex = OptionIndex;
	Parms.OldIndex = OldIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_LawSetting.BPUI_LawSetting_C.Completed_930C2B454714C01FDC4461AB2637C842
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCommonActivatableWidget*         WidgetObject                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBPUI_LawSetting_C::Completed_930C2B454714C01FDC4461AB2637C842(class UCommonActivatableWidget* WidgetObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_LawSetting_C", "Completed_930C2B454714C01FDC4461AB2637C842");

	Params::BPUI_LawSetting_C_Completed_930C2B454714C01FDC4461AB2637C842 Parms{};

	Parms.WidgetObject = WidgetObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_LawSetting.BPUI_LawSetting_C.ExecuteUbergraph_BPUI_LawSetting
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_LawSetting_C::ExecuteUbergraph_BPUI_LawSetting(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_LawSetting_C", "ExecuteUbergraph_BPUI_LawSetting");

	Params::BPUI_LawSetting_C_ExecuteUbergraph_BPUI_LawSetting Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_LawSetting.BPUI_LawSetting_C.MacForceShowMouse
// (Public, BlueprintCallable, BlueprintEvent)

void UBPUI_LawSetting_C::MacForceShowMouse()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_LawSetting_C", "MacForceShowMouse");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPUI_LawSetting.BPUI_LawSetting_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_LawSetting_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_LawSetting_C", "PreConstruct");

	Params::BPUI_LawSetting_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

