#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_AudioSetting

#include "Basic.hpp"

#include "BPUI_AudioSetting_classes.hpp"
#include "BPUI_AudioSetting_parameters.hpp"


namespace SDK
{

// Function BPUI_AudioSetting.BPUI_AudioSetting_C.BndEvt__BPUI_Setting_BPUI_Setting_SurroundSound_K2Node_ComponentBoundEvent_45_OnSettingChooseComboBoxOptionDelegate__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UHTUI_SettingOptionSlot*          OptionSlotWidget                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const class FName&                      OptionID                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OptionIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OldIndex                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_AudioSetting_C::BndEvt__BPUI_Setting_BPUI_Setting_SurroundSound_K2Node_ComponentBoundEvent_45_OnSettingChooseComboBoxOptionDelegate__DelegateSignature(class UHTUI_SettingOptionSlot* OptionSlotWidget, const class FName& OptionID, int32 OptionIndex, int32 OldIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_AudioSetting_C", "BndEvt__BPUI_Setting_BPUI_Setting_SurroundSound_K2Node_ComponentBoundEvent_45_OnSettingChooseComboBoxOptionDelegate__DelegateSignature");

	Params::BPUI_AudioSetting_C_BndEvt__BPUI_Setting_BPUI_Setting_SurroundSound_K2Node_ComponentBoundEvent_45_OnSettingChooseComboBoxOptionDelegate__DelegateSignature Parms{};

	Parms.OptionSlotWidget = OptionSlotWidget;
	Parms.OptionID = OptionID;
	Parms.OptionIndex = OptionIndex;
	Parms.OldIndex = OldIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_AudioSetting.BPUI_AudioSetting_C.ExecuteUbergraph_BPUI_AudioSetting
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_AudioSetting_C::ExecuteUbergraph_BPUI_AudioSetting(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_AudioSetting_C", "ExecuteUbergraph_BPUI_AudioSetting");

	Params::BPUI_AudioSetting_C_ExecuteUbergraph_BPUI_AudioSetting Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

