#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_ComboBoxListItem

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HTGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPUI_ComboBoxListItem.BPUI_ComboBoxListItem_C
// 0x0010 (0x0A10 - 0x0A00)
class UBPUI_ComboBoxListItem_C final : public UHTUI_ComboBoxListItem
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0A00(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	double                                        MyTargetWidth;                                     // 0x0A08(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BPUI_ComboBoxListItem(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPUI_ComboBoxListItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPUI_ComboBoxListItem_C")
	}
	static class UBPUI_ComboBoxListItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPUI_ComboBoxListItem_C>();
	}
};
DUMPER7_ASSERTS_UBPUI_ComboBoxListItem_C;

}

