#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_RadioBox_Table_2

#include "Basic.hpp"

#include "BPUI_RadioBox_Table_2_classes.hpp"
#include "BPUI_RadioBox_Table_2_parameters.hpp"


namespace SDK
{

// Function BPUI_RadioBox_Table_2.BPUI_RadioBox_Table_2_C.BndEvt__BPUI_RadioBox_Table_W_HTButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBPUI_RadioBox_Table_2_C::BndEvt__BPUI_RadioBox_Table_W_HTButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_RadioBox_Table_2_C", "BndEvt__BPUI_RadioBox_Table_W_HTButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature");

	Params::BPUI_RadioBox_Table_2_C_BndEvt__BPUI_RadioBox_Table_W_HTButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_RadioBox_Table_2.BPUI_RadioBox_Table_2_C.BndEvt__BPUI_RadionBox_Table_RadioBox_K2Node_ComponentBoundEvent_4_OnUnSelectedDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWidget*                          InWidget                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBPUI_RadioBox_Table_2_C::BndEvt__BPUI_RadionBox_Table_RadioBox_K2Node_ComponentBoundEvent_4_OnUnSelectedDelegate__DelegateSignature(class UWidget* InWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_RadioBox_Table_2_C", "BndEvt__BPUI_RadionBox_Table_RadioBox_K2Node_ComponentBoundEvent_4_OnUnSelectedDelegate__DelegateSignature");

	Params::BPUI_RadioBox_Table_2_C_BndEvt__BPUI_RadionBox_Table_RadioBox_K2Node_ComponentBoundEvent_4_OnUnSelectedDelegate__DelegateSignature Parms{};

	Parms.InWidget = InWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_RadioBox_Table_2.BPUI_RadioBox_Table_2_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBPUI_RadioBox_Table_2_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_RadioBox_Table_2_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPUI_RadioBox_Table_2.BPUI_RadioBox_Table_2_C.ExecuteUbergraph_BPUI_RadioBox_Table_2
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_RadioBox_Table_2_C::ExecuteUbergraph_BPUI_RadioBox_Table_2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_RadioBox_Table_2_C", "ExecuteUbergraph_BPUI_RadioBox_Table_2");

	Params::BPUI_RadioBox_Table_2_C_ExecuteUbergraph_BPUI_RadioBox_Table_2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_RadioBox_Table_2.BPUI_RadioBox_Table_2_C.OnMouseEnter
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UBPUI_RadioBox_Table_2_C::OnMouseEnter(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_RadioBox_Table_2_C", "OnMouseEnter");

	Params::BPUI_RadioBox_Table_2_C_OnMouseEnter Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_RadioBox_Table_2.BPUI_RadioBox_Table_2_C.OnMouseLeave
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UBPUI_RadioBox_Table_2_C::OnMouseLeave(const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_RadioBox_Table_2_C", "OnMouseLeave");

	Params::BPUI_RadioBox_Table_2_C_OnMouseLeave Parms{};

	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}

}

