#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_ComboBox_2

#include "Basic.hpp"

#include "BPUI_ComboBox_2_classes.hpp"
#include "BPUI_ComboBox_2_parameters.hpp"


namespace SDK
{

// Function BPUI_ComboBox_2.BPUI_ComboBox_2_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBPUI_ComboBox_2_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_ComboBox_2_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPUI_ComboBox_2.BPUI_ComboBox_2_C.ExecuteUbergraph_BPUI_ComboBox_2
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_ComboBox_2_C::ExecuteUbergraph_BPUI_ComboBox_2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_ComboBox_2_C", "ExecuteUbergraph_BPUI_ComboBox_2");

	Params::BPUI_ComboBox_2_C_ExecuteUbergraph_BPUI_ComboBox_2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

