#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HandmadeScroll

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass HandmadeScroll.HandmadeScroll_C
// 0x0000 (0x0040 - 0x0040)
class UHandmadeScroll_C final : public UCommonTextScrollStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("HandmadeScroll_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"HandmadeScroll_C")
	}
	static class UHandmadeScroll_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHandmadeScroll_C>();
	}
};
DUMPER7_ASSERTS_UHandmadeScroll_C;

}

