#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_QuickMenuSettings_KeyboardMenu

#include "Basic.hpp"

#include "WB_QuickMenuSettings_KeyboardMenu_classes.hpp"
#include "WB_QuickMenuSettings_KeyboardMenu_parameters.hpp"


namespace SDK
{

// Function WB_QuickMenuSettings_KeyboardMenu.WB_QuickMenuSettings_KeyboardMenu_C.BndEvt__WB_QuickMenuSettings_KeyboardMenu_HTButton_122_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWB_QuickMenuSettings_KeyboardMenu_C::BndEvt__WB_QuickMenuSettings_KeyboardMenu_HTButton_122_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_KeyboardMenu_C", "BndEvt__WB_QuickMenuSettings_KeyboardMenu_HTButton_122_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_QuickMenuSettings_KeyboardMenu.WB_QuickMenuSettings_KeyboardMenu_C.BP_ActivateFragmentWidget
// (Event, Public, BlueprintEvent)
// Parameters:
// class UOverlay*                         InOverlay                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_KeyboardMenu_C::BP_ActivateFragmentWidget(class UOverlay* InOverlay, int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_KeyboardMenu_C", "BP_ActivateFragmentWidget");

	Params::WB_QuickMenuSettings_KeyboardMenu_C_BP_ActivateFragmentWidget Parms{};

	Parms.InOverlay = InOverlay;
	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_QuickMenuSettings_KeyboardMenu.WB_QuickMenuSettings_KeyboardMenu_C.BP_DeactivateFragmentWidget
// (Event, Public, BlueprintEvent)
// Parameters:
// class UOverlay*                         InOverlay                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_KeyboardMenu_C::BP_DeactivateFragmentWidget(class UOverlay* InOverlay, int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_KeyboardMenu_C", "BP_DeactivateFragmentWidget");

	Params::WB_QuickMenuSettings_KeyboardMenu_C_BP_DeactivateFragmentWidget Parms{};

	Parms.InOverlay = InOverlay;
	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_QuickMenuSettings_KeyboardMenu.WB_QuickMenuSettings_KeyboardMenu_C.BP_OnEditorModeStateChanged
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    InbIsEditing                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_KeyboardMenu_C::BP_OnEditorModeStateChanged(bool InbIsEditing)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_KeyboardMenu_C", "BP_OnEditorModeStateChanged");

	Params::WB_QuickMenuSettings_KeyboardMenu_C_BP_OnEditorModeStateChanged Parms{};

	Parms.InbIsEditing = InbIsEditing;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_QuickMenuSettings_KeyboardMenu.WB_QuickMenuSettings_KeyboardMenu_C.BP_OnOptionButtonSelected
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UHTUI_QuickMenuSettings_OptionBtn*OptionButton                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_KeyboardMenu_C::BP_OnOptionButtonSelected(class UHTUI_QuickMenuSettings_OptionBtn* OptionButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_KeyboardMenu_C", "BP_OnOptionButtonSelected");

	Params::WB_QuickMenuSettings_KeyboardMenu_C_BP_OnOptionButtonSelected Parms{};

	Parms.OptionButton = OptionButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_QuickMenuSettings_KeyboardMenu.WB_QuickMenuSettings_KeyboardMenu_C.ExecuteUbergraph_WB_QuickMenuSettings_KeyboardMenu
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_KeyboardMenu_C::ExecuteUbergraph_WB_QuickMenuSettings_KeyboardMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_KeyboardMenu_C", "ExecuteUbergraph_WB_QuickMenuSettings_KeyboardMenu");

	Params::WB_QuickMenuSettings_KeyboardMenu_C_ExecuteUbergraph_WB_QuickMenuSettings_KeyboardMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

