#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_QuickMenuSettings_OptionBtn

#include "Basic.hpp"

#include "WB_QuickMenuSettings_OptionBtn_classes.hpp"
#include "WB_QuickMenuSettings_OptionBtn_parameters.hpp"


namespace SDK
{

// Function WB_QuickMenuSettings_OptionBtn.WB_QuickMenuSettings_OptionBtn_C.BP_OnSelectionChanged
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bSelected                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_OptionBtn_C::BP_OnSelectionChanged(bool bSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_OptionBtn_C", "BP_OnSelectionChanged");

	Params::WB_QuickMenuSettings_OptionBtn_C_BP_OnSelectionChanged Parms{};

	Parms.bSelected = bSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_QuickMenuSettings_OptionBtn.WB_QuickMenuSettings_OptionBtn_C.ExecuteUbergraph_WB_QuickMenuSettings_OptionBtn
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_QuickMenuSettings_OptionBtn_C::ExecuteUbergraph_WB_QuickMenuSettings_OptionBtn(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_QuickMenuSettings_OptionBtn_C", "ExecuteUbergraph_WB_QuickMenuSettings_OptionBtn");

	Params::WB_QuickMenuSettings_OptionBtn_C_ExecuteUbergraph_WB_QuickMenuSettings_OptionBtn Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

