#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_QuickMenuSettings_KeyboardMenu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HTGame_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_QuickMenuSettings_KeyboardMenu.WB_QuickMenuSettings_KeyboardMenu_C
// 0x0060 (0x0440 - 0x03E0)
class UWB_QuickMenuSettings_KeyboardMenu_C final : public UHTUI_QuickMenuSettings_KeyboardMenu
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_1;                                           // 0x03E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHTButton*                              HTButton_122;                                      // 0x03F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWB_QuickMenuFragmentActive_C*          FragmentActive_8;                                  // 0x03F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWB_QuickMenuFragmentActive_C*          FragmentActive_7;                                  // 0x0400(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWB_QuickMenuFragmentActive_C*          FragmentActive_6;                                  // 0x0408(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWB_QuickMenuFragmentActive_C*          FragmentActive_5;                                  // 0x0410(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWB_QuickMenuFragmentActive_C*          FragmentActive_4;                                  // 0x0418(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWB_QuickMenuFragmentActive_C*          FragmentActive_3;                                  // 0x0420(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWB_QuickMenuFragmentActive_C*          FragmentActive_2;                                  // 0x0428(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWB_QuickMenuFragmentActive_C*          FragmentActive;                                    // 0x0430(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           CanvasPanelIcons;                                  // 0x0438(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void BndEvt__WB_QuickMenuSettings_KeyboardMenu_HTButton_122_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void BP_ActivateFragmentWidget(class UOverlay* InOverlay, int32 Index_0);
	void BP_DeactivateFragmentWidget(class UOverlay* InOverlay, int32 Index_0);
	void BP_OnEditorModeStateChanged(bool InbIsEditing);
	void BP_OnOptionButtonSelected(class UHTUI_QuickMenuSettings_OptionBtn* OptionButton);
	void ExecuteUbergraph_WB_QuickMenuSettings_KeyboardMenu(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WB_QuickMenuSettings_KeyboardMenu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WB_QuickMenuSettings_KeyboardMenu_C")
	}
	static class UWB_QuickMenuSettings_KeyboardMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_QuickMenuSettings_KeyboardMenu_C>();
	}
};
DUMPER7_ASSERTS_UWB_QuickMenuSettings_KeyboardMenu_C;

}

